# Generated by Django 5.0.3 on 2024-07-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_status'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tickets',
            field=models.ManyToManyField(blank=True, null=True, to='ticket.ticket'),
        ),
    ]
